title: "Проджеки и мысли"
description: Projects and thoughts
url: "http://dub.podval.org"
author: "Leonid Dubinsky"
email: dub@podval.org
timezone: "America/New_York"
favicon: favicon.jpeg
google-analytics: "G-32JBCGFJ1T"
paginate-posts: 10
header-pages:
  - notes/index.md
  - posts
  - tags
  - graph

graph:
  enabled: true
  exclude-path-prefixes:
    - days

social:
  github:  dubinsky
  twitter: leoniddubinsky
  linkedin: leoniddubinsky
