title: "Проджеки и мысли"
description: Projects and thoughts
url: "http://dub.podval.org"
author: "Leonid Dubinsky"
email: dub@podval.org
timezone: "America/New_York"

header-pages:
  - /tags.html
  - /notes/index
  - /posts

exclude:
  - build.gradle
  - bundle
#  - CNAME
  - gradle
  - gradlew
  - gradlew.bat
  - settings.gradle
  - src

analytics:
  google: UA-18415116-1

social:
  github:  dubinsky
  twitter: leoniddubinsky
  linkedin: leoniddubinsky
