plugins {
  id 'io.github.ben-manes.versions' version '0.61.0'
  id 'scala'
  id 'application'
}

description = 'Financial Calculations'

application.mainClass = 'org.podval.finance.Main'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

scala.scalaVersion = '3.8.4'

// There is no Java in the project :)
project.gradle.startParameter.excludedTaskNames.add('compileJava')

tasks.withType(ScalaCompile).configureEach {
  scalaCompileOptions.with {
    additionalParameters = [
      '-new-syntax',
      '-feature',
      '-language:strictEquality',
      '-source:future'
    ]
  }
}

def isNonStable = { String version ->
  boolean stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  String regex = /^[0-9,.v-]+(-r)?$/
  return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
  rejectVersionIf {
    isNonStable(it.candidate.version)
  }
}
